#!/bin/bash

source <(curl -s https://raw.githubusercontent.com/BeckenrandschwimmerTim/proxmox/main/misc/main.func)

header_info
func_app_title
func_check_if_root

# Eval script dir
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

mkdir -p $DIR/sync_files_to_network_drive
mkdir -p $DIR/misc

cd $DIR/misc
curl https://raw.githubusercontent.com/BeckenrandschwimmerTim/proxmox/main/misc/main.func -o main.func

cd $DIR/sync_files_to_network_drive
curl https://raw.githubusercontent.com/BeckenrandschwimmerTim/openmediavault/main/sync_files_to_network_drive/sync_files_to_network_drive.sh -o sync_files_to_network_drive.sh
chmod +x sync_files_to_network_drive.sh
